[global]
pprof = ":6062"

# data center id
dc = "dc1"

# internet ip
addr = "127.0.0.1"

[webrtc]
ice = ["stun:stun.l.google.com:19302"]

# Range of ports that ion accepts WebRTC traffic on
ephemeral-udp-port-range = [5000, 6000]

[rtp]
# listen port
port = 6666

[log]
level = "info"
# level = "debug"

[etcd]
# ["ip:port", "ip:port"]
addrs = ["etcd:2379"]

[nats]
url = "nats://nats:4222"
